server:
  port: 8004
spring:
  datasource:
    url: jdbc:mysql://db1:3306/jpa-java0722?serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
   hibernate:
      ddl-auto: update
   show-sql: true
  application:
    name: UserProvider01
version: UserProvider01-update